#!/bin/sh
# Generated by autogen.sh
version=`cat VERSION`
dst=fluentd-$version
rm -rf $dst
mkdir $dst || exit 1
cp -fpR lib bin $dst/ || exit 1
mkdir -p $dst/deps || exit 1
cp deps/*.gem deps/ruby-*.tar.bz2 $dst/deps/
cp README.rdoc README COPYING NEWS ChangeLog AUTHORS INSTALL NOTICE \
    configure.in Makefile.in Makefile.am configure aclocal.m4 \
    Rakefile VERSION fluent.conf make_dist.sh \
    $dst/ || exit 1
cp -f README.rdoc $dst/README || exit 1
mkdir -p $dst/ac || exit 1
cp ac/* $dst/ac/ || exit 1
tar czvf $dst.tar.gz $dst || exit 1
rm -rf $dst

