blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/fluent/fluentd/discussions
    about: I have questions about Fluentd and plugins. Please ask and answer questions at https://github.com/fluent/fluentd/discussions
feedback_testimonials:
  - name: Feedback a Fluentd Use-Case/Testimonial
    url: https://github.com/fluent/fluentd-website/issues/new?template=testimonials.yml
    about: Feedback your Fluentd use-case/testimonial, How do you use Fluentd in your service?
