name: RucoCop Security & Performance Check

on:
  push:
    paths-ignore:
      - '*.md'
      - 'lib/fluent/version.rb'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'lib/fluent/version.rb'
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  rubocop:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0']
    name: Ruby ${{ matrix.ruby-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle install
          gem install rubocop-performance
      - name: Run RuboCop
        run: rubocop
